accounts:
- capkpi/accounts/*
- capkpi/controllers/accounts_controller.py
- capkpi/controllers/taxes_and_totals.py

stock:
- capkpi/stock/*
- capkpi/controllers/stock_controller.py
- capkpi/controllers/item_variant.py

assets:
- capkpi/assets/*

regional:
- capkpi/regional/*

selling:
- capkpi/selling/*
- capkpi/controllers/selling_controller.py

buying:
- capkpi/buying/*
- capkpi/controllers/buying_controller.py

support:
- capkpi/support/*

POS:
- pos*

ecommerce:
- capkpi/e_commerce/*

maintenance:
- capkpi/maintenance/*

manufacturing:
- capkpi/manufacturing/*

crm:
- capkpi/crm/*

HR:
- capkpi/hr/*

payroll:
- capkpi/payroll*

projects:
- capkpi/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['capkpi/**/*.py']
  all: ['!capkpi/**/test*.py']
